declare module 'framework7-icons/react' {
	type Framework7Icon = React.FC<React.HTMLAttributes<SVGSVGElement>>

	export const Airplane: Framework7Icon
	export const Alarm: Framework7Icon
	export const AlarmFill: Framework7Icon
	export const Alt: Framework7Icon
	export const Ant: Framework7Icon
	export const AntCircle: Framework7Icon
	export const AntCircleFill: Framework7Icon
	export const AntFill: Framework7Icon
	export const AntennaRadiowavesLeftRight: Framework7Icon
	export const App: Framework7Icon
	export const AppBadge: Framework7Icon
	export const AppBadgeFill: Framework7Icon
	export const AppFill: Framework7Icon
	export const Archivebox: Framework7Icon
	export const ArchiveboxFill: Framework7Icon
	export const Arrow2Circlepath: Framework7Icon
	export const Arrow2CirclepathCircle: Framework7Icon
	export const Arrow2CirclepathCircleFill: Framework7Icon
	export const Arrow2Squarepath: Framework7Icon
	export const Arrow3Trianglepath: Framework7Icon
	export const ArrowBranch: Framework7Icon
	export const ArrowClockwise: Framework7Icon
	export const ArrowClockwiseCircle: Framework7Icon
	export const ArrowClockwiseCircleFill: Framework7Icon
	export const ArrowCounterclockwise: Framework7Icon
	export const ArrowCounterclockwiseCircle: Framework7Icon
	export const ArrowCounterclockwiseCircleFill: Framework7Icon
	export const ArrowDown: Framework7Icon
	export const ArrowDownCircle: Framework7Icon
	export const ArrowDownCircleFill: Framework7Icon
	export const ArrowDownDoc: Framework7Icon
	export const ArrowDownDocFill: Framework7Icon
	export const ArrowDownLeft: Framework7Icon
	export const ArrowDownLeftCircle: Framework7Icon
	export const ArrowDownLeftCircleFill: Framework7Icon
	export const ArrowDownLeftSquare: Framework7Icon
	export const ArrowDownLeftSquareFill: Framework7Icon
	export const ArrowDownRight: Framework7Icon
	export const ArrowDownRightArrowUpLeft: Framework7Icon
	export const ArrowDownRightCircle: Framework7Icon
	export const ArrowDownRightCircleFill: Framework7Icon
	export const ArrowDownRightSquare: Framework7Icon
	export const ArrowDownRightSquareFill: Framework7Icon
	export const ArrowDownSquare: Framework7Icon
	export const ArrowDownSquareFill: Framework7Icon
	export const ArrowDownToLine: Framework7Icon
	export const ArrowDownToLineAlt: Framework7Icon
	export const ArrowLeft: Framework7Icon
	export const ArrowLeftCircle: Framework7Icon
	export const ArrowLeftCircleFill: Framework7Icon
	export const ArrowLeftRight: Framework7Icon
	export const ArrowLeftRightCircle: Framework7Icon
	export const ArrowLeftRightCircleFill: Framework7Icon
	export const ArrowLeftRightSquare: Framework7Icon
	export const ArrowLeftRightSquareFill: Framework7Icon
	export const ArrowLeftSquare: Framework7Icon
	export const ArrowLeftSquareFill: Framework7Icon
	export const ArrowLeftToLine: Framework7Icon
	export const ArrowLeftToLineAlt: Framework7Icon
	export const ArrowMerge: Framework7Icon
	export const ArrowRight: Framework7Icon
	export const ArrowRightArrowLeft: Framework7Icon
	export const ArrowRightArrowLeftCircle: Framework7Icon
	export const ArrowRightArrowLeftCircleFill: Framework7Icon
	export const ArrowRightArrowLeftSquare: Framework7Icon
	export const ArrowRightArrowLeftSquareFill: Framework7Icon
	export const ArrowRightCircle: Framework7Icon
	export const ArrowRightCircleFill: Framework7Icon
	export const ArrowRightSquare: Framework7Icon
	export const ArrowRightSquareFill: Framework7Icon
	export const ArrowRightToLine: Framework7Icon
	export const ArrowRightToLineAlt: Framework7Icon
	export const ArrowSwap: Framework7Icon
	export const ArrowTurnDownLeft: Framework7Icon
	export const ArrowTurnDownRight: Framework7Icon
	export const ArrowTurnLeftDown: Framework7Icon
	export const ArrowTurnLeftUp: Framework7Icon
	export const ArrowTurnRightDown: Framework7Icon
	export const ArrowTurnRightUp: Framework7Icon
	export const ArrowTurnUpLeft: Framework7Icon
	export const ArrowTurnUpRight: Framework7Icon
	export const ArrowUp: Framework7Icon
	export const ArrowUpArrowDown: Framework7Icon
	export const ArrowUpArrowDownCircle: Framework7Icon
	export const ArrowUpArrowDownCircleFill: Framework7Icon
	export const ArrowUpArrowDownSquare: Framework7Icon
	export const ArrowUpArrowDownSquareFill: Framework7Icon
	export const ArrowUpBin: Framework7Icon
	export const ArrowUpBinFill: Framework7Icon
	export const ArrowUpCircle: Framework7Icon
	export const ArrowUpCircleFill: Framework7Icon
	export const ArrowUpDoc: Framework7Icon
	export const ArrowUpDocFill: Framework7Icon
	export const ArrowUpDown: Framework7Icon
	export const ArrowUpDownCircle: Framework7Icon
	export const ArrowUpDownCircleFill: Framework7Icon
	export const ArrowUpDownSquare: Framework7Icon
	export const ArrowUpDownSquareFill: Framework7Icon
	export const ArrowUpLeft: Framework7Icon
	export const ArrowUpLeftArrowDownRight: Framework7Icon
	export const ArrowUpLeftCircle: Framework7Icon
	export const ArrowUpLeftCircleFill: Framework7Icon
	export const ArrowUpLeftSquare: Framework7Icon
	export const ArrowUpLeftSquareFill: Framework7Icon
	export const ArrowUpRight: Framework7Icon
	export const ArrowUpRightCircle: Framework7Icon
	export const ArrowUpRightCircleFill: Framework7Icon
	export const ArrowUpRightDiamond: Framework7Icon
	export const ArrowUpRightDiamondFill: Framework7Icon
	export const ArrowUpRightSquare: Framework7Icon
	export const ArrowUpRightSquareFill: Framework7Icon
	export const ArrowUpSquare: Framework7Icon
	export const ArrowUpSquareFill: Framework7Icon
	export const ArrowUpToLine: Framework7Icon
	export const ArrowUpToLineAlt: Framework7Icon
	export const ArrowUturnDown: Framework7Icon
	export const ArrowUturnDownCircle: Framework7Icon
	export const ArrowUturnDownCircleFill: Framework7Icon
	export const ArrowUturnDownSquare: Framework7Icon
	export const ArrowUturnDownSquareFill: Framework7Icon
	export const ArrowUturnLeft: Framework7Icon
	export const ArrowUturnLeftCircle: Framework7Icon
	export const ArrowUturnLeftCircleFill: Framework7Icon
	export const ArrowUturnLeftSquare: Framework7Icon
	export const ArrowUturnLeftSquareFill: Framework7Icon
	export const ArrowUturnRight: Framework7Icon
	export const ArrowUturnRightCircle: Framework7Icon
	export const ArrowUturnRightCircleFill: Framework7Icon
	export const ArrowUturnRightSquare: Framework7Icon
	export const ArrowUturnRightSquareFill: Framework7Icon
	export const ArrowUturnUp: Framework7Icon
	export const ArrowUturnUpCircle: Framework7Icon
	export const ArrowUturnUpCircleFill: Framework7Icon
	export const ArrowUturnUpSquare: Framework7Icon
	export const ArrowUturnUpSquareFill: Framework7Icon
	export const ArrowshapeTurnUpLeft: Framework7Icon
	export const ArrowshapeTurnUpLeft2: Framework7Icon
	export const ArrowshapeTurnUpLeft2Fill: Framework7Icon
	export const ArrowshapeTurnUpLeftCircle: Framework7Icon
	export const ArrowshapeTurnUpLeftCircleFill: Framework7Icon
	export const ArrowshapeTurnUpLeftFill: Framework7Icon
	export const ArrowshapeTurnUpRight: Framework7Icon
	export const ArrowshapeTurnUpRightCircle: Framework7Icon
	export const ArrowshapeTurnUpRightCircleFill: Framework7Icon
	export const ArrowshapeTurnUpRightFill: Framework7Icon
	export const ArrowtriangleDown: Framework7Icon
	export const ArrowtriangleDownCircle: Framework7Icon
	export const ArrowtriangleDownCircleFill: Framework7Icon
	export const ArrowtriangleDownFill: Framework7Icon
	export const ArrowtriangleDownSquare: Framework7Icon
	export const ArrowtriangleDownSquareFill: Framework7Icon
	export const ArrowtriangleLeft: Framework7Icon
	export const ArrowtriangleLeftCircle: Framework7Icon
	export const ArrowtriangleLeftCircleFill: Framework7Icon
	export const ArrowtriangleLeftFill: Framework7Icon
	export const ArrowtriangleLeftSquare: Framework7Icon
	export const ArrowtriangleLeftSquareFill: Framework7Icon
	export const ArrowtriangleRight: Framework7Icon
	export const ArrowtriangleRightCircle: Framework7Icon
	export const ArrowtriangleRightCircleFill: Framework7Icon
	export const ArrowtriangleRightFill: Framework7Icon
	export const ArrowtriangleRightSquare: Framework7Icon
	export const ArrowtriangleRightSquareFill: Framework7Icon
	export const ArrowtriangleUp: Framework7Icon
	export const ArrowtriangleUpCircle: Framework7Icon
	export const ArrowtriangleUpCircleFill: Framework7Icon
	export const ArrowtriangleUpFill: Framework7Icon
	export const ArrowtriangleUpSquare: Framework7Icon
	export const ArrowtriangleUpSquareFill: Framework7Icon
	export const AsteriskCircle: Framework7Icon
	export const AsteriskCircleFill: Framework7Icon
	export const At: Framework7Icon
	export const AtBadgeMinus: Framework7Icon
	export const AtBadgePlus: Framework7Icon
	export const AtCircle: Framework7Icon
	export const AtCircleFill: Framework7Icon
	export const Backward: Framework7Icon
	export const BackwardEnd: Framework7Icon
	export const BackwardEndAlt: Framework7Icon
	export const BackwardEndAltFill: Framework7Icon
	export const BackwardEndFill: Framework7Icon
	export const BackwardFill: Framework7Icon
	export const BadgePlusRadiowavesRight: Framework7Icon
	export const Bag: Framework7Icon
	export const BagBadgeMinus: Framework7Icon
	export const BagBadgePlus: Framework7Icon
	export const BagFill: Framework7Icon
	export const BagFillBadgeMinus: Framework7Icon
	export const BagFillBadgePlus: Framework7Icon
	export const Bandage: Framework7Icon
	export const BandageFill: Framework7Icon
	export const Barcode: Framework7Icon
	export const BarcodeViewfinder: Framework7Icon
	export const Bars: Framework7Icon
	export const Battery0: Framework7Icon
	export const Battery100: Framework7Icon
	export const Battery25: Framework7Icon
	export const BedDouble: Framework7Icon
	export const BedDoubleFill: Framework7Icon
	export const Bell: Framework7Icon
	export const Bell: Framework7Icon
	export const BellCircle: Framework7Icon
	export const BellCircleFill: Framework7Icon
	export const BellFill: Framework7Icon
	export const BellSlash: Framework7Icon
	export const BellSlashFill: Framework7Icon
	export const BinXmark: Framework7Icon
	export const BinXmarkFill: Framework7Icon
	export const Bitcoin: Framework7Icon
	export const BitcoinCircle: Framework7Icon
	export const BitcoinCircleFill: Framework7Icon
	export const Bold: Framework7Icon
	export const BoldItalicUnderline: Framework7Icon
	export const BoldUnderline: Framework7Icon
	export const Bolt: Framework7Icon
	export const BoltBadgeA: Framework7Icon
	export const BoltBadgeAFill: Framework7Icon
	export const BoltCircle: Framework7Icon
	export const BoltCircleFill: Framework7Icon
	export const BoltFill: Framework7Icon
	export const BoltHorizontal: Framework7Icon
	export const BoltHorizontalCircle: Framework7Icon
	export const BoltHorizontalCircleFill: Framework7Icon
	export const BoltHorizontalFill: Framework7Icon
	export const BoltSlash: Framework7Icon
	export const BoltSlashFill: Framework7Icon
	export const Book: Framework7Icon
	export const BookCircle: Framework7Icon
	export const BookCircleFill: Framework7Icon
	export const BookFill: Framework7Icon
	export const Bookmark: Framework7Icon
	export const BookmarkFill: Framework7Icon
	export const Briefcase: Framework7Icon
	export const BriefcaseFill: Framework7Icon
	export const BubbleLeft: Framework7Icon
	export const BubbleLeftBubbleRight: Framework7Icon
	export const BubbleLeftBubbleRightFill: Framework7Icon
	export const BubbleLeftFill: Framework7Icon
	export const BubbleMiddleBottom: Framework7Icon
	export const BubbleMiddleBottomFill: Framework7Icon
	export const BubbleMiddleTop: Framework7Icon
	export const BubbleMiddleTopFill: Framework7Icon
	export const BubbleRight: Framework7Icon
	export const BubbleRightFill: Framework7Icon
	export const Building: Framework7Icon
	export const Building2: Framework7Icon
	export const Building2CropCircle: Framework7Icon
	export const Building2CropCircleFill: Framework7Icon
	export const Building2Fill: Framework7Icon
	export const BuildingColumns: Framework7Icon
	export const BuildingColumnsFill: Framework7Icon
	export const BuildingFill: Framework7Icon
	export const Burn: Framework7Icon
	export const Burst: Framework7Icon
	export const BurstFill: Framework7Icon
	export const Calendar: Framework7Icon
	export const CalendarBadgeMinus: Framework7Icon
	export const CalendarBadgePlus: Framework7Icon
	export const CalendarCircle: Framework7Icon
	export const CalendarCircleFill: Framework7Icon
	export const CalendarToday: Framework7Icon
	export const Camera: Framework7Icon
	export const CameraCircle: Framework7Icon
	export const CameraCircleFill: Framework7Icon
	export const CameraFill: Framework7Icon
	export const CameraFilters: Framework7Icon
	export const CameraOnRectangle: Framework7Icon
	export const CameraOnRectangleFill: Framework7Icon
	export const CameraRotate: Framework7Icon
	export const CameraRotateFill: Framework7Icon
	export const CameraViewfinder: Framework7Icon
	export const Capslock: Framework7Icon
	export const CapslockFill: Framework7Icon
	export const Capsule: Framework7Icon
	export const CapsuleFill: Framework7Icon
	export const CaptionsBubble: Framework7Icon
	export const CaptionsBubbleFill: Framework7Icon
	export const CarFill: Framework7Icon
	export const Cart: Framework7Icon
	export const CartBadgeMinus: Framework7Icon
	export const CartBadgePlus: Framework7Icon
	export const CartFill: Framework7Icon
	export const CartFillBadgeMinus: Framework7Icon
	export const CartFillBadgePlus: Framework7Icon
	export const Cat: Framework7Icon
	export const ChartBar: Framework7Icon
	export const ChartBarAltFill: Framework7Icon
	export const ChartBarCircle: Framework7Icon
	export const ChartBarCircleFill: Framework7Icon
	export const ChartBarFill: Framework7Icon
	export const ChartBarSquare: Framework7Icon
	export const ChartBarSquareFill: Framework7Icon
	export const ChartPie: Framework7Icon
	export const ChartPieFill: Framework7Icon
	export const ChatBubble: Framework7Icon
	export const ChatBubble2: Framework7Icon
	export const ChatBubble2Fill: Framework7Icon
	export const ChatBubbleFill: Framework7Icon
	export const ChatBubbleText: Framework7Icon
	export const ChatBubbleTextFill: Framework7Icon
	export const Checkmark: Framework7Icon
	export const Checkmark2: Framework7Icon
	export const CheckmarkAlt: Framework7Icon
	export const CheckmarkAltCircle: Framework7Icon
	export const CheckmarkAltCircleFill: Framework7Icon
	export const CheckmarkCircle: Framework7Icon
	export const CheckmarkCircleFill: Framework7Icon
	export const CheckmarkRectangle: Framework7Icon
	export const CheckmarkRectangleFill: Framework7Icon
	export const CheckmarkSeal: Framework7Icon
	export const CheckmarkSealFill: Framework7Icon
	export const CheckmarkShield: Framework7Icon
	export const CheckmarkShieldFill: Framework7Icon
	export const CheckmarkSquare: Framework7Icon
	export const CheckmarkSquareFill: Framework7Icon
	export const ChevronCompactDown: Framework7Icon
	export const ChevronCompactLeft: Framework7Icon
	export const ChevronCompactRight: Framework7Icon
	export const ChevronCompactUp: Framework7Icon
	export const ChevronDown: Framework7Icon
	export const ChevronDownCircle: Framework7Icon
	export const ChevronDownCircleFill: Framework7Icon
	export const ChevronDownSquare: Framework7Icon
	export const ChevronDownSquareFill: Framework7Icon
	export const ChevronLeft: Framework7Icon
	export const ChevronLeft2: Framework7Icon
	export const ChevronLeftCircle: Framework7Icon
	export const ChevronLeftCircleFill: Framework7Icon
	export const ChevronLeftSlashChevronRight: Framework7Icon
	export const ChevronLeftSquare: Framework7Icon
	export const ChevronLeftSquareFill: Framework7Icon
	export const ChevronRight: Framework7Icon
	export const ChevronRight2: Framework7Icon
	export const ChevronRightCircle: Framework7Icon
	export const ChevronRightCircleFill: Framework7Icon
	export const ChevronRightSquare: Framework7Icon
	export const ChevronRightSquareFill: Framework7Icon
	export const ChevronUp: Framework7Icon
	export const ChevronUpChevronDown: Framework7Icon
	export const ChevronUpCircle: Framework7Icon
	export const ChevronUpCircleFill: Framework7Icon
	export const ChevronUpSquare: Framework7Icon
	export const ChevronUpSquareFill: Framework7Icon
	export const Circle: Framework7Icon
	export const CircleBottomthirdSplit: Framework7Icon
	export const CircleFill: Framework7Icon
	export const CircleGrid3x3: Framework7Icon
	export const CircleGrid3x3Fill: Framework7Icon
	export const CircleGridHex: Framework7Icon
	export const CircleGridHexFill: Framework7Icon
	export const CircleLefthalfFill: Framework7Icon
	export const CircleRighthalfFill: Framework7Icon
	export const Clear: Framework7Icon
	export const ClearFill: Framework7Icon
	export const Clock: Framework7Icon
	export const ClockFill: Framework7Icon
	export const Cloud: Framework7Icon
	export const CloudBolt: Framework7Icon
	export const CloudBoltFill: Framework7Icon
	export const CloudBoltRain: Framework7Icon
	export const CloudBoltRainFill: Framework7Icon
	export const CloudDownload: Framework7Icon
	export const CloudDownloadFill: Framework7Icon
	export const CloudDrizzle: Framework7Icon
	export const CloudDrizzleFill: Framework7Icon
	export const CloudFill: Framework7Icon
	export const CloudFog: Framework7Icon
	export const CloudFogFill: Framework7Icon
	export const CloudHail: Framework7Icon
	export const CloudHailFill: Framework7Icon
	export const CloudHeavyrain: Framework7Icon
	export const CloudHeavyrainFill: Framework7Icon
	export const CloudMoon: Framework7Icon
	export const CloudMoonBolt: Framework7Icon
	export const CloudMoonBoltFill: Framework7Icon
	export const CloudMoonFill: Framework7Icon
	export const CloudMoonRain: Framework7Icon
	export const CloudMoonRainFill: Framework7Icon
	export const CloudRain: Framework7Icon
	export const CloudRainFill: Framework7Icon
	export const CloudSleet: Framework7Icon
	export const CloudSleetFill: Framework7Icon
	export const CloudSnow: Framework7Icon
	export const CloudSnowFill: Framework7Icon
	export const CloudSun: Framework7Icon
	export const CloudSunBolt: Framework7Icon
	export const CloudSunBoltFill: Framework7Icon
	export const CloudSunFill: Framework7Icon
	export const CloudSunRain: Framework7Icon
	export const CloudSunRainFill: Framework7Icon
	export const CloudUpload: Framework7Icon
	export const CloudUploadFill: Framework7Icon
	export const Command: Framework7Icon
	export const Compass: Framework7Icon
	export const CompassFill: Framework7Icon
	export const Control: Framework7Icon
	export const Creditcard: Framework7Icon
	export const CreditcardFill: Framework7Icon
	export const Crop: Framework7Icon
	export const CropRotate: Framework7Icon
	export const Cube: Framework7Icon
	export const CubeBox: Framework7Icon
	export const CubeBoxFill: Framework7Icon
	export const CubeFill: Framework7Icon
	export const CursorRays: Framework7Icon
	export const DecreaseIndent: Framework7Icon
	export const DecreaseQuotelevel: Framework7Icon
	export const DeleteLeft: Framework7Icon
	export const DeleteLeftFill: Framework7Icon
	export const DeleteRight: Framework7Icon
	export const DeleteRightFill: Framework7Icon
	export const Desktopcomputer: Framework7Icon
	export const DeviceDesktop: Framework7Icon
	export const DeviceLaptop: Framework7Icon
	export const DevicePhoneLandscape: Framework7Icon
	export const DevicePhonePortrait: Framework7Icon
	export const DeviceTabletLandscape: Framework7Icon
	export const DeviceTabletPortrait: Framework7Icon
	export const Dial: Framework7Icon
	export const DialFill: Framework7Icon
	export const Divide: Framework7Icon
	export const DivideCircle: Framework7Icon
	export const DivideCircleFill: Framework7Icon
	export const DivideSquare: Framework7Icon
	export const DivideSquareFill: Framework7Icon
	export const Doc: Framework7Icon
	export const DocAppend: Framework7Icon
	export const DocChart: Framework7Icon
	export const DocChartFill: Framework7Icon
	export const DocCheckmark: Framework7Icon
	export const DocCheckmarkFill: Framework7Icon
	export const DocCircle: Framework7Icon
	export const DocCircleFill: Framework7Icon
	export const DocFill: Framework7Icon
	export const DocOnClipboard: Framework7Icon
	export const DocOnClipboardFill: Framework7Icon
	export const DocOnDoc: Framework7Icon
	export const DocOnDocFill: Framework7Icon
	export const DocPerson: Framework7Icon
	export const DocPersonFill: Framework7Icon
	export const DocPlaintext: Framework7Icon
	export const DocRichtext: Framework7Icon
	export const DocText: Framework7Icon
	export const DocTextFill: Framework7Icon
	export const DocTextSearch: Framework7Icon
	export const DocTextViewfinder: Framework7Icon
	export const Dog: Framework7Icon
	export const DotRadiowavesLeftRight: Framework7Icon
	export const DotRadiowavesRight: Framework7Icon
	export const DotSquare: Framework7Icon
	export const DotSquareFill: Framework7Icon
	export const DownloadCircle: Framework7Icon
	export const DownloadCircleFill: Framework7Icon
	export const Drop: Framework7Icon
	export const DropFill: Framework7Icon
	export const DropTriangle: Framework7Icon
	export const DropTriangleFill: Framework7Icon
	export const Ear: Framework7Icon
	export const Eject: Framework7Icon
	export const EjectFill: Framework7Icon
	export const EllipsesBubble: Framework7Icon
	export const EllipsesBubbleFill: Framework7Icon
	export const Ellipsis: Framework7Icon
	export const EllipsisCircle: Framework7Icon
	export const EllipsisCircleFill: Framework7Icon
	export const EllipsisVertical: Framework7Icon
	export const EllipsisVerticalCircle: Framework7Icon
	export const EllipsisVerticalCircleFill: Framework7Icon
	export const Envelope: Framework7Icon
	export const EnvelopeBadge: Framework7Icon
	export const EnvelopeBadgeFill: Framework7Icon
	export const EnvelopeCircle: Framework7Icon
	export const EnvelopeCircleFill: Framework7Icon
	export const EnvelopeFill: Framework7Icon
	export const EnvelopeOpen: Framework7Icon
	export const EnvelopeOpenFill: Framework7Icon
	export const Equal: Framework7Icon
	export const EqualCircle: Framework7Icon
	export const EqualCircleFill: Framework7Icon
	export const EqualSquare: Framework7Icon
	export const EqualSquareFill: Framework7Icon
	export const Escape: Framework7Icon
	export const Exclamationmark: Framework7Icon
	export const ExclamationmarkBubble: Framework7Icon
	export const ExclamationmarkBubbleFill: Framework7Icon
	export const ExclamationmarkCircle: Framework7Icon
	export const ExclamationmarkCircleFill: Framework7Icon
	export const ExclamationmarkOctagon: Framework7Icon
	export const ExclamationmarkOctagonFill: Framework7Icon
	export const ExclamationmarkShield: Framework7Icon
	export const ExclamationmarkShieldFill: Framework7Icon
	export const ExclamationmarkSquare: Framework7Icon
	export const ExclamationmarkSquareFill: Framework7Icon
	export const ExclamationmarkTriangle: Framework7Icon
	export const ExclamationmarkTriangleFill: Framework7Icon
	export const Expand: Framework7Icon
	export const Eye: Framework7Icon
	export const EyeFill: Framework7Icon
	export const EyeSlash: Framework7Icon
	export const EyeSlashFill: Framework7Icon
	export const Eyedropper: Framework7Icon
	export const EyedropperFull: Framework7Icon
	export const EyedropperHalffull: Framework7Icon
	export const Eyeglasses: Framework7Icon
	export const FCursive: Framework7Icon
	export const FCursiveCircle: Framework7Icon
	export const FCursiveCircleFill: Framework7Icon
	export const FaceSmiling: Framework7Icon
	export const FaceSmilingFill: Framework7Icon
	export const Facemask: Framework7Icon
	export const FacemaskFill: Framework7Icon
	export const Film: Framework7Icon
	export const FilmFill: Framework7Icon
	export const Flag: Framework7Icon
	export const FlagCircle: Framework7Icon
	export const FlagCircleFill: Framework7Icon
	export const FlagFill: Framework7Icon
	export const FlagSlash: Framework7Icon
	export const FlagSlashFill: Framework7Icon
	export const Flame: Framework7Icon
	export const FlameFill: Framework7Icon
	export const FloppyDisk: Framework7Icon
	export const Flowchart: Framework7Icon
	export const FlowchartFill: Framework7Icon
	export const Folder: Framework7Icon
	export const FolderBadgeMinus: Framework7Icon
	export const FolderBadgePersonCrop: Framework7Icon
	export const FolderBadgePlus: Framework7Icon
	export const FolderCircle: Framework7Icon
	export const FolderCircleFill: Framework7Icon
	export const FolderFill: Framework7Icon
	export const FolderFillBadgeMinus: Framework7Icon
	export const FolderFillBadgePersonCrop: Framework7Icon
	export const FolderFillBadgePlus: Framework7Icon
	export const Forward: Framework7Icon
	export const ForwardEnd: Framework7Icon
	export const ForwardEndAlt: Framework7Icon
	export const ForwardEndAltFill: Framework7Icon
	export const ForwardEndFill: Framework7Icon
	export const ForwardFill: Framework7Icon
	export const Function: Framework7Icon
	export const Funnel: Framework7Icon
	export const FunnelFill: Framework7Icon
	export const Fx: Framework7Icon
	export const Gamecontroller: Framework7Icon
	export const GamecontrollerAltFill: Framework7Icon
	export const GamecontrollerFill: Framework7Icon
	export const Gauge: Framework7Icon
	export const GaugeBadgeMinus: Framework7Icon
	export const GaugeBadgePlus: Framework7Icon
	export const Gear: Framework7Icon
	export const GearAlt: Framework7Icon
	export const GearAltFill: Framework7Icon
	export const Gift: Framework7Icon
	export const GiftAlt: Framework7Icon
	export const GiftAltFill: Framework7Icon
	export const GiftFill: Framework7Icon
	export const Giftcard: Framework7Icon
	export const GiftcardFill: Framework7Icon
	export const Globe: Framework7Icon
	export const Gobackward: Framework7Icon
	export const Gobackward10: Framework7Icon
	export const Gobackward15: Framework7Icon
	export const Gobackward30: Framework7Icon
	export const Gobackward45: Framework7Icon
	export const Gobackward60: Framework7Icon
	export const Gobackward75: Framework7Icon
	export const Gobackward90: Framework7Icon
	export const GobackwardMinus: Framework7Icon
	export const Goforward: Framework7Icon
	export const Goforward10: Framework7Icon
	export const Goforward15: Framework7Icon
	export const Goforward30: Framework7Icon
	export const Goforward45: Framework7Icon
	export const Goforward60: Framework7Icon
	export const Goforward75: Framework7Icon
	export const Goforward90: Framework7Icon
	export const GoforwardPlus: Framework7Icon
	export const GraphCircle: Framework7Icon
	export const GraphCircleFill: Framework7Icon
	export const GraphSquare: Framework7Icon
	export const GraphSquareFill: Framework7Icon
	export const Greaterthan: Framework7Icon
	export const GreaterthanCircle: Framework7Icon
	export const GreaterthanCircleFill: Framework7Icon
	export const GreaterthanSquare: Framework7Icon
	export const GreaterthanSquareFill: Framework7Icon
	export const Grid: Framework7Icon
	export const GridCircle: Framework7Icon
	export const GridCircleFill: Framework7Icon
	export const Guitars: Framework7Icon
	export const Hammer: Framework7Icon
	export const HammerFill: Framework7Icon
	export const HandDraw: Framework7Icon
	export const HandDrawFill: Framework7Icon
	export const HandPointLeft: Framework7Icon
	export const HandPointLeftFill: Framework7Icon
	export const HandPointRight: Framework7Icon
	export const HandPointRightFill: Framework7Icon
	export const HandRaised: Framework7Icon
	export const HandRaisedFill: Framework7Icon
	export const HandRaisedSlash: Framework7Icon
	export const HandRaisedSlashFill: Framework7Icon
	export const HandThumbsdown: Framework7Icon
	export const HandThumbsdownFill: Framework7Icon
	export const HandThumbsup: Framework7Icon
	export const HandThumbsupFill: Framework7Icon
	export const Hare: Framework7Icon
	export const HareFill: Framework7Icon
	export const Headphones: Framework7Icon
	export const Heart: Framework7Icon
	export const HeartCircle: Framework7Icon
	export const HeartCircleFill: Framework7Icon
	export const HeartFill: Framework7Icon
	export const HeartSlash: Framework7Icon
	export const HeartSlashCircle: Framework7Icon
	export const HeartSlashCircleFill: Framework7Icon
	export const HeartSlashFill: Framework7Icon
	export const Helm: Framework7Icon
	export const Hexagon: Framework7Icon
	export const HexagonFill: Framework7Icon
	export const Hifispeaker: Framework7Icon
	export const HifispeakerFill: Framework7Icon
	export const Hourglass: Framework7Icon
	export const HourglassBottomhalfFill: Framework7Icon
	export const HourglassTophalfFill: Framework7Icon
	export const House: Framework7Icon
	export const HouseAlt: Framework7Icon
	export const HouseAltFill: Framework7Icon
	export const HouseFill: Framework7Icon
	export const Hurricane: Framework7Icon
	export const IncreaseIndent: Framework7Icon
	export const IncreaseQuotelevel: Framework7Icon
	export const Infinite: Framework7Icon
	export const Info: Framework7Icon
	export const InfoCircle: Framework7Icon
	export const InfoCircleFill: Framework7Icon
	export const Italic: Framework7Icon
	export const Keyboard: Framework7Icon
	export const KeyboardChevronCompactDown: Framework7Icon
	export const LargecircleFillCircle: Framework7Icon
	export const Lasso: Framework7Icon
	export const Layers: Framework7Icon
	export const LayersAlt: Framework7Icon
	export const LayersAltFill: Framework7Icon
	export const LayersFill: Framework7Icon
	export const LeafArrowCirclepath: Framework7Icon
	export const Lessthan: Framework7Icon
	export const LessthanCircle: Framework7Icon
	export const LessthanCircleFill: Framework7Icon
	export const LessthanSquare: Framework7Icon
	export const LessthanSquareFill: Framework7Icon
	export const LightMax: Framework7Icon
	export const LightMin: Framework7Icon
	export const Lightbulb: Framework7Icon
	export const LightbulbFill: Framework7Icon
	export const LightbulbSlash: Framework7Icon
	export const LightbulbSlashFill: Framework7Icon
	export const LineHorizontal3: Framework7Icon
	export const LineHorizontal3Decrease: Framework7Icon
	export const LineHorizontal3DecreaseCircle: Framework7Icon
	export const LineHorizontal3DecreaseCircleFill: Framework7Icon
	export const Link: Framework7Icon
	export const LinkCircle: Framework7Icon
	export const LinkCircleFill: Framework7Icon
	export const ListBullet: Framework7Icon
	export const ListBulletBelowRectangle: Framework7Icon
	export const ListBulletIndent: Framework7Icon
	export const ListDash: Framework7Icon
	export const ListNumber: Framework7Icon
	export const ListNumberRtl: Framework7Icon
	export const Location: Framework7Icon
	export const LocationCircle: Framework7Icon
	export const LocationCircleFill: Framework7Icon
	export const LocationFill: Framework7Icon
	export const LocationNorth: Framework7Icon
	export const LocationNorthFill: Framework7Icon
	export const LocationNorthLine: Framework7Icon
	export const LocationNorthLineFill: Framework7Icon
	export const LocationSlash: Framework7Icon
	export const LocationSlashFill: Framework7Icon
	export const Lock: Framework7Icon
	export const LockCircle: Framework7Icon
	export const LockCircleFill: Framework7Icon
	export const LockFill: Framework7Icon
	export const LockOpen: Framework7Icon
	export const LockOpenFill: Framework7Icon
	export const LockRotation: Framework7Icon
	export const LockRotationOpen: Framework7Icon
	export const LockShield: Framework7Icon
	export const LockShieldFill: Framework7Icon
	export const LockSlash: Framework7Icon
	export const LockSlashFill: Framework7Icon
	export const LogoAndroid: Framework7Icon
	export const LogoAndroidText: Framework7Icon
	export const LogoApple: Framework7Icon
	export const LogoFacebook: Framework7Icon
	export const LogoGithub: Framework7Icon
	export const LogoGoogle: Framework7Icon
	export const LogoGoogleText: Framework7Icon
	export const LogoGoogleplus: Framework7Icon
	export const LogoInstagram: Framework7Icon
	export const LogoIos: Framework7Icon
	export const LogoLinkedin: Framework7Icon
	export const LogoMacos: Framework7Icon
	export const LogoMicrosoft: Framework7Icon
	export const LogoRss: Framework7Icon
	export const LogoStackoverflow: Framework7Icon
	export const LogoTwitter: Framework7Icon
	export const LogoWindows: Framework7Icon
	export const Macwindow: Framework7Icon
	export const Map: Framework7Icon
	export const MapFill: Framework7Icon
	export const MapPin: Framework7Icon
	export const MapPinEllipse: Framework7Icon
	export const MapPinSlash: Framework7Icon
	export const Memories: Framework7Icon
	export const MemoriesBadgeMinus: Framework7Icon
	export const MemoriesBadgePlus: Framework7Icon
	export const Menu: Framework7Icon
	export const Metronome: Framework7Icon
	export const Mic: Framework7Icon
	export const MicCircle: Framework7Icon
	export const MicCircleFill: Framework7Icon
	export const MicFill: Framework7Icon
	export const MicSlash: Framework7Icon
	export const MicSlashFill: Framework7Icon
	export const Minus: Framework7Icon
	export const MinusCircle: Framework7Icon
	export const MinusCircleFill: Framework7Icon
	export const MinusRectangle: Framework7Icon
	export const MinusRectangleFill: Framework7Icon
	export const MinusSlashPlus: Framework7Icon
	export const MinusSquare: Framework7Icon
	export const MinusSquareFill: Framework7Icon
	export const MoneyDollar: Framework7Icon
	export const MoneyDollarCircle: Framework7Icon
	export const MoneyDollarCircleFill: Framework7Icon
	export const MoneyEuro: Framework7Icon
	export const MoneyEuroCircle: Framework7Icon
	export const MoneyEuroCircleFill: Framework7Icon
	export const MoneyPound: Framework7Icon
	export const MoneyPoundCircle: Framework7Icon
	export const MoneyPoundCircleFill: Framework7Icon
	export const MoneyRubl: Framework7Icon
	export const MoneyRublCircle: Framework7Icon
	export const MoneyRublCircleFill: Framework7Icon
	export const MoneyYen: Framework7Icon
	export const MoneyYenCircle: Framework7Icon
	export const MoneyYenCircleFill: Framework7Icon
	export const Moon: Framework7Icon
	export const MoonCircle: Framework7Icon
	export const MoonCircleFill: Framework7Icon
	export const MoonFill: Framework7Icon
	export const MoonStars: Framework7Icon
	export const MoonStarsFill: Framework7Icon
	export const MoonZzz: Framework7Icon
	export const MoonZzzFill: Framework7Icon
	export const Move: Framework7Icon
	export const Multiply: Framework7Icon
	export const MultiplyCircle: Framework7Icon
	export const MultiplyCircleFill: Framework7Icon
	export const MultiplySquare: Framework7Icon
	export const MultiplySquareFill: Framework7Icon
	export const MusicAlbums: Framework7Icon
	export const MusicAlbumsFill: Framework7Icon
	export const MusicHouse: Framework7Icon
	export const MusicHouseFill: Framework7Icon
	export const MusicMic: Framework7Icon
	export const MusicNote: Framework7Icon
	export const MusicNote2: Framework7Icon
	export const MusicNoteList: Framework7Icon
	export const Nosign: Framework7Icon
	export const Number: Framework7Icon
	export const NumberCircle: Framework7Icon
	export const NumberCircleFill: Framework7Icon
	export const NumberSquare: Framework7Icon
	export const NumberSquareFill: Framework7Icon
	export const Option: Framework7Icon
	export const Paintbrush: Framework7Icon
	export const PaintbrushFill: Framework7Icon
	export const Pano: Framework7Icon
	export const PanoFill: Framework7Icon
	export const Paperclip: Framework7Icon
	export const Paperplane: Framework7Icon
	export const PaperplaneFill: Framework7Icon
	export const Paragraph: Framework7Icon
	export const Pause: Framework7Icon
	export const PauseCircle: Framework7Icon
	export const PauseCircleFill: Framework7Icon
	export const PauseFill: Framework7Icon
	export const PauseRectangle: Framework7Icon
	export const PauseRectangleFill: Framework7Icon
	export const Paw: Framework7Icon
	export const Pencil: Framework7Icon
	export const PencilCircle: Framework7Icon
	export const PencilCircleFill: Framework7Icon
	export const PencilEllipsisRectangle: Framework7Icon
	export const PencilOutline: Framework7Icon
	export const PencilSlash: Framework7Icon
	export const Percent: Framework7Icon
	export const Person: Framework7Icon
	export const Person2: Framework7Icon
	export const Person2Alt: Framework7Icon
	export const Person2Fill: Framework7Icon
	export const Person2SquareStack: Framework7Icon
	export const Person2SquareStackFill: Framework7Icon
	export const Person3: Framework7Icon
	export const Person3Fill: Framework7Icon
	export const PersonAlt: Framework7Icon
	export const PersonAltCircle: Framework7Icon
	export const PersonAltCircleFill: Framework7Icon
	export const PersonBadgeMinus: Framework7Icon
	export const PersonBadgeMinusFill: Framework7Icon
	export const PersonBadgePlus: Framework7Icon
	export const PersonBadgePlusFill: Framework7Icon
	export const PersonCircle: Framework7Icon
	export const PersonCircleFill: Framework7Icon
	export const PersonCropCircle: Framework7Icon
	export const PersonCropCircleBadgeCheckmark: Framework7Icon
	export const PersonCropCircleBadgeExclam: Framework7Icon
	export const PersonCropCircleBadgeMinus: Framework7Icon
	export const PersonCropCircleBadgePlus: Framework7Icon
	export const PersonCropCircleBadgeXmark: Framework7Icon
	export const PersonCropCircleFill: Framework7Icon
	export const PersonCropCircleFillBadgeCheckmark: Framework7Icon
	export const PersonCropCircleFillBadgeExclam: Framework7Icon
	export const PersonCropCircleFillBadgeMinus: Framework7Icon
	export const PersonCropCircleFillBadgePlus: Framework7Icon
	export const PersonCropCircleFillBadgeXmark: Framework7Icon
	export const PersonCropRectangle: Framework7Icon
	export const PersonCropRectangleFill: Framework7Icon
	export const PersonCropSquare: Framework7Icon
	export const PersonCropSquareFill: Framework7Icon
	export const PersonFill: Framework7Icon
	export const Personalhotspot: Framework7Icon
	export const Perspective: Framework7Icon
	export const Phone: Framework7Icon
	export const PhoneArrowDownLeft: Framework7Icon
	export const PhoneArrowRight: Framework7Icon
	export const PhoneArrowUpRight: Framework7Icon
	export const PhoneBadgePlus: Framework7Icon
	export const PhoneCircle: Framework7Icon
	export const PhoneCircleFill: Framework7Icon
	export const PhoneDown: Framework7Icon
	export const PhoneDownCircle: Framework7Icon
	export const PhoneDownCircleFill: Framework7Icon
	export const PhoneDownFill: Framework7Icon
	export const PhoneFill: Framework7Icon
	export const PhoneFillArrowDownLeft: Framework7Icon
	export const PhoneFillArrowRight: Framework7Icon
	export const PhoneFillArrowUpRight: Framework7Icon
	export const PhoneFillBadgePlus: Framework7Icon
	export const Photo: Framework7Icon
	export const PhotoFill: Framework7Icon
	export const PhotoFillOnRectangleFill: Framework7Icon
	export const PhotoOnRectangle: Framework7Icon
	export const Piano: Framework7Icon
	export const Pin: Framework7Icon
	export const PinFill: Framework7Icon
	export const PinSlash: Framework7Icon
	export const PinSlashFill: Framework7Icon
	export const Placemark: Framework7Icon
	export const PlacemarkFill: Framework7Icon
	export const Play: Framework7Icon
	export const PlayCircle: Framework7Icon
	export const PlayCircleFill: Framework7Icon
	export const PlayFill: Framework7Icon
	export const PlayRectangle: Framework7Icon
	export const PlayRectangleFill: Framework7Icon
	export const Playpause: Framework7Icon
	export const PlaypauseFill: Framework7Icon
	export const Plus: Framework7Icon
	export const PlusApp: Framework7Icon
	export const PlusAppFill: Framework7Icon
	export const PlusBubble: Framework7Icon
	export const PlusBubbleFill: Framework7Icon
	export const PlusCircle: Framework7Icon
	export const PlusCircleFill: Framework7Icon
	export const PlusRectangle: Framework7Icon
	export const PlusRectangleFill: Framework7Icon
	export const PlusRectangleFillOnRectangleFill: Framework7Icon
	export const PlusRectangleOnRectangle: Framework7Icon
	export const PlusSlashMinus: Framework7Icon
	export const PlusSquare: Framework7Icon
	export const PlusSquareFill: Framework7Icon
	export const PlusSquareFillOnSquareFill: Framework7Icon
	export const PlusSquareOnSquare: Framework7Icon
	export const Plusminus: Framework7Icon
	export const PlusminusCircle: Framework7Icon
	export const PlusminusCircleFill: Framework7Icon
	export const PoultryLeg: Framework7Icon
	export const Power: Framework7Icon
	export const Printer: Framework7Icon
	export const PrinterFill: Framework7Icon
	export const Projective: Framework7Icon
	export const Purchased: Framework7Icon
	export const PurchasedCircle: Framework7Icon
	export const PurchasedCircleFill: Framework7Icon
	export const Qrcode: Framework7Icon
	export const QrcodeViewfinder: Framework7Icon
	export const Question: Framework7Icon
	export const QuestionCircle: Framework7Icon
	export const QuestionCircleFill: Framework7Icon
	export const QuestionDiamond: Framework7Icon
	export const QuestionDiamondFill: Framework7Icon
	export const QuestionSquare: Framework7Icon
	export const QuestionSquareFill: Framework7Icon
	export const QuoteBubble: Framework7Icon
	export const QuoteBubbleFill: Framework7Icon
	export const RadiowavesLeft: Framework7Icon
	export const RadiowavesRight: Framework7Icon
	export const Rays: Framework7Icon
	export const Recordingtape: Framework7Icon
	export const Rectangle: Framework7Icon
	export const Rectangle3Offgrid: Framework7Icon
	export const Rectangle3OffgridFill: Framework7Icon
	export const RectangleArrowUpRightArrowDownLeft: Framework7Icon
	export const RectangleArrowUpRightArrowDownLeftSlash: Framework7Icon
	export const RectangleBadgeCheckmark: Framework7Icon
	export const RectangleBadgeXmark: Framework7Icon
	export const RectangleCompressVertical: Framework7Icon
	export const RectangleDock: Framework7Icon
	export const RectangleExpandVertical: Framework7Icon
	export const RectangleFill: Framework7Icon
	export const RectangleFillBadgeCheckmark: Framework7Icon
	export const RectangleFillBadgeXmark: Framework7Icon
	export const RectangleFillOnRectangleAngledFill: Framework7Icon
	export const RectangleFillOnRectangleFill: Framework7Icon
	export const RectangleGrid1x2: Framework7Icon
	export const RectangleGrid1x2Fill: Framework7Icon
	export const RectangleGrid2x2: Framework7Icon
	export const RectangleGrid2x2Fill: Framework7Icon
	export const RectangleGrid3x2: Framework7Icon
	export const RectangleGrid3x2Fill: Framework7Icon
	export const RectangleOnRectangle: Framework7Icon
	export const RectangleOnRectangleAngled: Framework7Icon
	export const RectanglePaperclip: Framework7Icon
	export const RectangleSplit3x1: Framework7Icon
	export const RectangleSplit3x1Fill: Framework7Icon
	export const RectangleSplit3x3: Framework7Icon
	export const RectangleSplit3x3Fill: Framework7Icon
	export const RectangleStack: Framework7Icon
	export const RectangleStackBadgeMinus: Framework7Icon
	export const RectangleStackBadgePersonCrop: Framework7Icon
	export const RectangleStackBadgePlus: Framework7Icon
	export const RectangleStackFill: Framework7Icon
	export const RectangleStackFillBadgeMinus: Framework7Icon
	export const RectangleStackFillBadgePersonCrop: Framework7Icon
	export const RectangleStackFillBadgePlus: Framework7Icon
	export const RectangleStackPersonCrop: Framework7Icon
	export const RectangleStackPersonCropFill: Framework7Icon
	export const Repeat: Framework7Icon
	export const Repeat1: Framework7Icon
	export const Resize: Framework7Icon
	export const ResizeH: Framework7Icon
	export const ResizeV: Framework7Icon
	export const Return: Framework7Icon
	export const Rhombus: Framework7Icon
	export const RhombusFill: Framework7Icon
	export const Rocket: Framework7Icon
	export const RocketFill: Framework7Icon
	export const Rosette: Framework7Icon
	export const RotateLeft: Framework7Icon
	export const RotateLeftFill: Framework7Icon
	export const RotateLeftFill: Framework7Icon
	export const RotateRight: Framework7Icon
	export const RotateRightFill: Framework7Icon
	export const Scissors: Framework7Icon
	export const ScissorsAlt: Framework7Icon
	export const Scope: Framework7Icon
	export const Scribble: Framework7Icon
	export const Search: Framework7Icon
	export const SearchCircle: Framework7Icon
	export const SearchCircleFill: Framework7Icon
	export const SelectionPinInOut: Framework7Icon
	export const Shield: Framework7Icon
	export const ShieldFill: Framework7Icon
	export const ShieldLefthalfFill: Framework7Icon
	export const ShieldSlash: Framework7Icon
	export const ShieldSlashFill: Framework7Icon
	export const Shift: Framework7Icon
	export const ShiftFill: Framework7Icon
	export const Shippingbox: Framework7Icon
	export const ShippingboxFill: Framework7Icon
	export const Shuffle: Framework7Icon
	export const SidebarLeft: Framework7Icon
	export const SidebarRight: Framework7Icon
	export const Signature: Framework7Icon
	export const Skew: Framework7Icon
	export const SlashCircle: Framework7Icon
	export const SlashCircleFill: Framework7Icon
	export const SliderHorizontal3: Framework7Icon
	export const SliderHorizontalBelowRectangle: Framework7Icon
	export const Slowmo: Framework7Icon
	export const SmallcircleCircle: Framework7Icon
	export const SmallcircleCircleFill: Framework7Icon
	export const SmallcircleFillCircle: Framework7Icon
	export const SmallcircleFillCircleFill: Framework7Icon
	export const Smiley: Framework7Icon
	export const SmileyFill: Framework7Icon
	export const Smoke: Framework7Icon
	export const SmokeFill: Framework7Icon
	export const Snow: Framework7Icon
	export const SortDown: Framework7Icon
	export const SortDownCircle: Framework7Icon
	export const SortDownCircleFill: Framework7Icon
	export const SortUp: Framework7Icon
	export const SortUpCircle: Framework7Icon
	export const SortUpCircleFill: Framework7Icon
	export const Sparkles: Framework7Icon
	export const Speaker: Framework7Icon
	export const Speaker1: Framework7Icon
	export const Speaker1Fill: Framework7Icon
	export const Speaker2: Framework7Icon
	export const Speaker2Fill: Framework7Icon
	export const Speaker3: Framework7Icon
	export const Speaker3Fill: Framework7Icon
	export const SpeakerFill: Framework7Icon
	export const SpeakerSlash: Framework7Icon
	export const SpeakerSlashFill: Framework7Icon
	export const SpeakerSlashFillRtl: Framework7Icon
	export const SpeakerSlashRtl: Framework7Icon
	export const SpeakerZzz: Framework7Icon
	export const SpeakerZzzFill: Framework7Icon
	export const SpeakerZzzFillRtl: Framework7Icon
	export const SpeakerZzzRtl: Framework7Icon
	export const Speedometer: Framework7Icon
	export const Sportscourt: Framework7Icon
	export const SportscourtFill: Framework7Icon
	export const Square: Framework7Icon
	export const SquareArrowDown: Framework7Icon
	export const SquareArrowDownFill: Framework7Icon
	export const SquareArrowDownOnSquare: Framework7Icon
	export const SquareArrowDownOnSquareFill: Framework7Icon
	export const SquareArrowLeft: Framework7Icon
	export const SquareArrowLeftFill: Framework7Icon
	export const SquareArrowRight: Framework7Icon
	export const SquareArrowRightFill: Framework7Icon
	export const SquareArrowUp: Framework7Icon
	export const SquareArrowUpFill: Framework7Icon
	export const SquareArrowUpOnSquare: Framework7Icon
	export const SquareArrowUpOnSquareFill: Framework7Icon
	export const SquareFavorites: Framework7Icon
	export const SquareFavoritesAlt: Framework7Icon
	export const SquareFavoritesAltFill: Framework7Icon
	export const SquareFavoritesFill: Framework7Icon
	export const SquareFill: Framework7Icon
	export const SquareFillLineVerticalSquare: Framework7Icon
	export const SquareFillLineVerticalSquareFill: Framework7Icon
	export const SquareFillOnCircleFill: Framework7Icon
	export const SquareFillOnSquareFill: Framework7Icon
	export const SquareGrid2x2: Framework7Icon
	export const SquareGrid2x2Fill: Framework7Icon
	export const SquareGrid3x2: Framework7Icon
	export const SquareGrid3x2Fill: Framework7Icon
	export const SquareGrid4x3Fill: Framework7Icon
	export const SquareLefthalfFill: Framework7Icon
	export const SquareLineVerticalSquare: Framework7Icon
	export const SquareLineVerticalSquareFill: Framework7Icon
	export const SquareList: Framework7Icon
	export const SquareListFill: Framework7Icon
	export const SquareOnCircle: Framework7Icon
	export const SquareOnSquare: Framework7Icon
	export const SquarePencil: Framework7Icon
	export const SquarePencilFill: Framework7Icon
	export const SquareRighthalfFill: Framework7Icon
	export const SquareSplit1x2: Framework7Icon
	export const SquareSplit1x2Fill: Framework7Icon
	export const SquareSplit2x1: Framework7Icon
	export const SquareSplit2x1Fill: Framework7Icon
	export const SquareSplit2x2: Framework7Icon
	export const SquareSplit2x2Fill: Framework7Icon
	export const SquareStack: Framework7Icon
	export const SquareStack3dDownDottedline: Framework7Icon
	export const SquareStack3dDownRight: Framework7Icon
	export const SquareStack3dDownRightFill: Framework7Icon
	export const SquareStack3dUp: Framework7Icon
	export const SquareStack3dUpFill: Framework7Icon
	export const SquareStack3dUpSlash: Framework7Icon
	export const SquareStack3dUpSlashFill: Framework7Icon
	export const SquareStackFill: Framework7Icon
	export const SquaresBelowRectangle: Framework7Icon
	export const Star: Framework7Icon
	export const StarCircle: Framework7Icon
	export const StarCircleFill: Framework7Icon
	export const StarFill: Framework7Icon
	export const StarLefthalfFill: Framework7Icon
	export const StarSlash: Framework7Icon
	export const StarSlashFill: Framework7Icon
	export const Staroflife: Framework7Icon
	export const StaroflifeFill: Framework7Icon
	export const Status: Framework7Icon
	export const Sticker: Framework7Icon
	export const Stop: Framework7Icon
	export const StopCircle: Framework7Icon
	export const StopCircleFill: Framework7Icon
	export const StopFill: Framework7Icon
	export const Stopwatch: Framework7Icon
	export const StopwatchFill: Framework7Icon
	export const Strikethrough: Framework7Icon
	export const SuitClub: Framework7Icon
	export const SuitClubFill: Framework7Icon
	export const SuitDiamond: Framework7Icon
	export const SuitDiamondFill: Framework7Icon
	export const SuitHeart: Framework7Icon
	export const SuitHeartFill: Framework7Icon
	export const SuitSpade: Framework7Icon
	export const SuitSpadeFill: Framework7Icon
	export const Sum: Framework7Icon
	export const SunDust: Framework7Icon
	export const SunDustFill: Framework7Icon
	export const SunHaze: Framework7Icon
	export const SunHazeFill: Framework7Icon
	export const SunMax: Framework7Icon
	export const SunMaxFill: Framework7Icon
	export const SunMin: Framework7Icon
	export const SunMinFill: Framework7Icon
	export const Sunrise: Framework7Icon
	export const SunriseFill: Framework7Icon
	export const Sunset: Framework7Icon
	export const SunsetFill: Framework7Icon
	export const TBubble: Framework7Icon
	export const TBubbleFill: Framework7Icon
	export const Table: Framework7Icon
	export const TableBadgeMore: Framework7Icon
	export const TableBadgeMoreFill: Framework7Icon
	export const TableFill: Framework7Icon
	export const Tag: Framework7Icon
	export const TagCircle: Framework7Icon
	export const TagCircleFill: Framework7Icon
	export const TagFill: Framework7Icon
	export const TextAligncenter: Framework7Icon
	export const TextAlignleft: Framework7Icon
	export const TextAlignright: Framework7Icon
	export const TextAppend: Framework7Icon
	export const TextBadgeCheckmark: Framework7Icon
	export const TextBadgeMinus: Framework7Icon
	export const TextBadgePlus: Framework7Icon
	export const TextBadgeStar: Framework7Icon
	export const TextBadgeXmark: Framework7Icon
	export const TextBubble: Framework7Icon
	export const TextBubbleFill: Framework7Icon
	export const TextCursor: Framework7Icon
	export const TextInsert: Framework7Icon
	export const TextJustify: Framework7Icon
	export const TextJustifyleft: Framework7Icon
	export const TextJustifyright: Framework7Icon
	export const TextQuote: Framework7Icon
	export const Textbox: Framework7Icon
	export const Textformat: Framework7Icon
	export const Textformat123: Framework7Icon
	export const TextformatAbc: Framework7Icon
	export const TextformatAbcDottedunderline: Framework7Icon
	export const TextformatAlt: Framework7Icon
	export const TextformatSize: Framework7Icon
	export const TextformatSubscript: Framework7Icon
	export const TextformatSuperscript: Framework7Icon
	export const Thermometer: Framework7Icon
	export const ThermometerSnowflake: Framework7Icon
	export const ThermometerSun: Framework7Icon
	export const Ticket: Framework7Icon
	export const TicketFill: Framework7Icon
	export const Tickets: Framework7Icon
	export const TicketsFill: Framework7Icon
	export const Timelapse: Framework7Icon
	export const Timer: Framework7Icon
	export const TimerFill: Framework7Icon
	export const Today: Framework7Icon
	export const TodayFill: Framework7Icon
	export const Tornado: Framework7Icon
	export const Tortoise: Framework7Icon
	export const TortoiseFill: Framework7Icon
	export const TramFill: Framework7Icon
	export const Trash: Framework7Icon
	export const TrashCircle: Framework7Icon
	export const TrashCircleFill: Framework7Icon
	export const TrashFill: Framework7Icon
	export const TrashSlash: Framework7Icon
	export const TrashSlashFill: Framework7Icon
	export const Tray: Framework7Icon
	export const Tray2: Framework7Icon
	export const Tray2Fill: Framework7Icon
	export const TrayArrowDown: Framework7Icon
	export const TrayArrowDownFill: Framework7Icon
	export const TrayArrowUp: Framework7Icon
	export const TrayArrowUpFill: Framework7Icon
	export const TrayFill: Framework7Icon
	export const TrayFull: Framework7Icon
	export const TrayFullFill: Framework7Icon
	export const Tree: Framework7Icon
	export const Triangle: Framework7Icon
	export const TriangleFill: Framework7Icon
	export const TriangleLefthalfFill: Framework7Icon
	export const TriangleRighthalfFill: Framework7Icon
	export const Tropicalstorm: Framework7Icon
	export const Tuningfork: Framework7Icon
	export const Tv: Framework7Icon
	export const TvCircle: Framework7Icon
	export const TvCircleFill: Framework7Icon
	export const TvFill: Framework7Icon
	export const TvMusicNote: Framework7Icon
	export const TvMusicNoteFill: Framework7Icon
	export const UiwindowSplit2x1: Framework7Icon
	export const Umbrella: Framework7Icon
	export const UmbrellaFill: Framework7Icon
	export const Underline: Framework7Icon
	export const UploadCircle: Framework7Icon
	export const UploadCircleFill: Framework7Icon
	export const Videocam: Framework7Icon
	export const VideocamCircle: Framework7Icon
	export const VideocamCircleFill: Framework7Icon
	export const VideocamFill: Framework7Icon
	export const View2d: Framework7Icon
	export const View3d: Framework7Icon
	export const Viewfinder: Framework7Icon
	export const ViewfinderCircle: Framework7Icon
	export const ViewfinderCircleFill: Framework7Icon
	export const Wallet: Framework7Icon
	export const WalletFill: Framework7Icon
	export const WandRays: Framework7Icon
	export const WandRaysInverse: Framework7Icon
	export const WandStars: Framework7Icon
	export const WandStarsInverse: Framework7Icon
	export const Waveform: Framework7Icon
	export const WaveformCircle: Framework7Icon
	export const WaveformCircleFill: Framework7Icon
	export const WaveformPath: Framework7Icon
	export const WaveformPathBadgeMinus: Framework7Icon
	export const WaveformPathBadgePlus: Framework7Icon
	export const WaveformPathEcg: Framework7Icon
	export const Wifi: Framework7Icon
	export const WifiExclamationmark: Framework7Icon
	export const WifiSlash: Framework7Icon
	export const Wind: Framework7Icon
	export const WindSnow: Framework7Icon
	export const Wrench: Framework7Icon
	export const WrenchFill: Framework7Icon
	export const Xmark: Framework7Icon
	export const XmarkCircle: Framework7Icon
	export const XmarkCircleFill: Framework7Icon
	export const XmarkOctagon: Framework7Icon
	export const XmarkOctagonFill: Framework7Icon
	export const XmarkRectangle: Framework7Icon
	export const XmarkRectangleFill: Framework7Icon
	export const XmarkSeal: Framework7Icon
	export const XmarkSealFill: Framework7Icon
	export const XmarkShield: Framework7Icon
	export const XmarkShieldFill: Framework7Icon
	export const XmarkSquare: Framework7Icon
	export const XmarkSquareFill: Framework7Icon
	export const YinYang: Framework7Icon
	export const Zap: Framework7Icon
	export const ZapSlash: Framework7Icon
	export const ZoomIn: Framework7Icon
	export const ZoomOut: Framework7Icon
	export const Zzz: Framework7Icon
}
